### ISSUE TITLE
translate learn/typescript into Chinese

### ISSUE THREAD

**Issue by awxiaoxian2020** [reactjs/zh-hans.react.dev#1292]
https://github.com/reactjs/zh-hans.react.dev/blob/main/src/content/learn/typescript.md

**Comment by awxiaoxian2020** [comment]
@ysh199882 Please follow https://github.com/reactjs/zh-hans.react.dev/blob/main/TRANSLATION.md. I will assign this issue to you :)

**Comment by ysh199882** [comment]
> @ysh199882 Please follow https://github.com/reactjs/zh-hans.react.dev/blob/main/TRANSLATION.md. I will assign this issue to you :)请关注https://github.com/reactjs/zh-hans.react.dev/blob/main/TRANSLATION.md。我会把这个问题分配给你:)

好的
