### ISSUE TITLE
translate reference/react/use.md into Chinese

### ISSUE THREAD

**Issue by Yucohny** [reactjs/zh-hans.react.dev#1314]
translate reference/react/use.md into Chinese

**Comment by Yucohny** [comment]
Working

**Comment by li-jia-nan** [comment]
这个有人认领吗？可以让我来做吗？

**Comment by awxiaoxian2020** [comment]
@li-jia-nan 

@Yucohny 已经在翻了

**Comment by li-jia-nan** [comment]
> @Yucohny 已经在翻了

好的，还有其它的翻译任务吗？

**Comment by Yucohny** [comment]
> > @Yucohny 已经在翻了
> 
> 好的，还有其它的翻译任务吗？

没有了。之后每有一篇新的需要翻译的文章都会单独开一个 issue。

**Comment by li-jia-nan** [comment]
> 没有了。之后每有一篇新的需要翻译的文章都会单独开一个 issue。

好的，那我 watch 一下这个仓库吧

**Comment by Yucohny** [comment]
See https://github.com/reactjs/zh-hans.react.dev/pull/1315.
