### ISSUE TITLE
How to understand the word "taint" in the new APIs taintObjectReference and taintUniqueValue?

### ISSUE THREAD

**Issue by Yucohny** [reactjs/zh-hans.react.dev#1342]
I used to open an issue on react.dev to discuss the meaning of the word `taint` in the APIs. You can see https://github.com/reactjs/react.dev/issues/6343.
My opinion is that while `taint` can be directly understood as `污染` or `污点` in the field of computer science and in some related concepts (such as in Kubernetes), considering its current meaning in React-related APIs, I believe that when translating it into Chinese, we should not use words with a clearly negative connotation.
From the perspective of APIs, the meaning of "taint" seems more like labeling objects with special behavior. So, I think translating it as `标记` is appropriate. I will also use this meaning in the translated documentation.
Welcome everyone to discuss this issue.

**Comment by awxiaoxian2020** [comment]
See https://github.com/reactjs/react.dev/issues/6343#issuecomment-1767420377
