### ISSUE TITLE
关于 state 的中文翻译讨论

### ISSUE THREAD

**Issue by Yucohny** [reactjs/zh-hans.react.dev#1354]
See https://github.com/reactjs/zh-hans.react.dev/discussions/1126.

**Comment by Huxpro** [comment]
cc @awxiaoxian2020 can you follow up with your suggested guidances here?

**Comment by awxiaoxian2020** [comment]
@Huxpro 可以参见我在[术语表](https://github.com/reactjs/zh-hans.react.dev/wiki/The-Glossary-Sheet)中作出的粗略说明（表述确实有不清晰的地方）。所谓“概念的一部分”即指“状态管理”这样的情况。我们接下来的工作可能是补充相关例子。

**Comment by awxiaoxian2020** [comment]
考虑翻译已接近完成，这属于具体问题具体分析的范畴，这个 issue 就暂时关了。
