### ISSUE TITLE
关于 hydrate 的中文翻译讨论

### ISSUE THREAD

**Issue by Yucohny** [reactjs/zh-hans.react.dev#1355]
See https://github.com/reactjs/zh-hans.react.dev/discussions/1237.
目前采取的翻译方式是保留 hydrate 及单词的变形。

**Comment by Huxpro** [comment]
参考 https://github.com/vuejs-translations/docs-zh-cn/issues/2 与 https://github.com/vuejs/docs-next-zh-cn/pull/786

我的倾向是：

- hydrate (v.): 激活。如 “使用 JS 激活” （hydrate with JS）
- hydration (n.): 激活。

这样不需要区分“注水”和“水合”，而且比较生动

**Comment by awxiaoxian2020** [comment]
虽然使用“水”相关的意象词语略显奇怪，但是文档作者或者说开发者本就准备使用这一说法。

> **In React**, “hydration” **is** how React “attaches” to existing HTML that was already rendered by React in a server environment. 

可以发现，文档作者也特意强调了“hydration”在 React 中的特殊含义。

而且我询问了身边的一些 React 开发者，"注水"这一词语也被经常使用。

从我个人的角度来说，肯定是更喜欢“激活”这一翻译，但是确定下来，我认为需要更多的共识。

**Comment by Huxpro** [comment]
@awxiaoxian2020 你觉得有哪些方法可以收集更多信息和反馈？发个 Twitter?

**Comment by CoderSerio** [comment]
Hello, 这个讨论目前有结果吗

**Comment by kangnli** [comment]
请问有结果吗？目前在从事一些 react 书籍翻译的工作，遇到了这个问题

**Comment by Huxpro** [comment]
经过本站翻译主要维护者的讨论，我们达成了「激活」的共识，并将下来采用「激活」作为本网站对 hydrate 的翻译。

cc @CoderSerio @kangnli 感谢询问

**Comment by awxiaoxian2020** [comment]
考虑翻译的一致性、可读性和生动性，我们暂定该词翻译为“激活”，社区随后若有更好的意见，欢迎随时提出~
