### ISSUE TITLE
关于 fallback 的中文翻译讨论

### ISSUE THREAD

**Issue by Yucohny** [reactjs/zh-hans.react.dev#1356]
之前在 https://github.com/reactjs/zh-hans.react.dev/discussions/611#discussioncomment-7368151 与 https://github.com/reactjs/zh-hans.react.dev/pull/1131#discussion_r1168125832 等处中有过相关讨论，现在将关于 fallback 的中文翻译讨论单独开一篇 issue。
目前术语表规定文档中不翻译 fallback 而保留原文，不过 reviewer 也似乎并未注意这个问题，文档中也有多处将其翻译为了「回退」、「降级」等中文。
尽管 fallback 未必能称为专有名词，但是如果一定要翻译 fallback 的意思，希望能够讨论后形成确切的规范。

**Comment by Huxpro** [comment]
参考 <https://www.zhihu.com/question/21847989>:

> an alternative plan that may be used in an emergency. — New Oxford American Dictionary
后备，回退。

我目前的倾向是

- fallback (v.) : 回退。
- fallback (adj.) : 后备。如，后备脚本（fallback script）
- fallback (n.) : 后备方案。

**Comment by Yucohny** [comment]
> 参考 https://www.zhihu.com/question/21847989:
> 
> > an alternative plan that may be used in an emergency. — New Oxford American Dictionary
> > 后备，回退。
> 
> 我目前的倾向是
> 
> * fallback (v.) : 回退。
> * fallback (adj.) : 后备。如，后备脚本（fallback script）
> * fallback (n.) : 后备方案。

可以👍🏻

**Comment by awxiaoxian2020** [comment]
+1

**Comment by Yucohny** [comment]
> 参考 https://www.zhihu.com/question/21847989:
> 
> > an alternative plan that may be used in an emergency. — New Oxford American Dictionary
> > 后备，回退。
> 
> 我目前的倾向是
> 
> * fallback (v.) : 回退。
> * fallback (adj.) : 后备。如，后备脚本（fallback script）
> * fallback (n.) : 后备方案。

就将这个作为 fallback 的翻译规范吧，我找时间来调整一下已经翻译过的文档。

**Comment by Yucohny** [comment]
See https://github.com/reactjs/zh-hans.react.dev/pull/1360.

**Comment by alephpi** [comment]
fallback的功能是在没有任何配置的情况下采用默认方案以免程序失去合理控制的逻辑，翻译成“兜底方案”或“保底方案”如何？
