### ISSUE TITLE
Taint shouldn't be translated to 标记

### ISSUE THREAD

**Issue by Huxpro** [reactjs/zh-hans.react.dev#1359]
See my updated comments on <https://github.com/reactjs/react.dev/issues/6343>:

<img width="1043" alt="image" src="https://github.com/reactjs/zh-hans.react.dev/assets/5563315/7328c441-9ec9-4065-8325-a01b9e5dfc57">

**Comment by Huxpro** [comment]
We should consider words demonstrating undesirable quality, such as 污点、污迹

**Comment by Yucohny** [comment]
how about 
taint (n.) - 污点
taint (v.) - 污染
tainted (adj.) - 被污染的

**Comment by Huxpro** [comment]
@Yucohny 

After reading through several Chinese literature on taint checking and taint analysis e.g.
- <https://users.ece.cmu.edu/~youzhib/paper/chen2012.pdf>, I'd suggest

tainted (adj.) - 污点，如污点变量（tainted variable）
tainted (ved) - 被污染，如 xx 被污染 (variable is tainted)

N.B. "ved" means the past participle of "v." so technically it is the same with "taint (v.) - 污染"

**Comment by Huxpro** [comment]
Emm <https://www.jos.org.cn/html/2020/10/6063.htm> actually say "污染的"

**Comment by Huxpro** [comment]
Ok, I changed my mind

> taint (n.) - 污点
> taint (v.) - 污染
> tainted (adj.) - 被污染的

I think the above is good, except we'll also need:

> tainting (ving) - 污点标记

**Comment by Huxpro** [comment]
The detail can be iterated but we can start here to respect the tradition of 污点标记 at least

**Comment by Yucohny** [comment]
> Ok, I changed my mind
> 
> > taint (n.) - 污点
> > taint (v.) - 污染
> > tainted (adj.) - 被污染的
> 
> I think the above is good, except we'll also need something like:
> 
> * tainting (ving) - 污点标记
> 
> For sentences like "Do not rely solely on tainting for security. " where "tainting" is an active action

I think this explanation is pretty good. I'm considering making adjustments based on this explanation first.

**Comment by Yucohny** [comment]
搬运自 @Huxpro 
> tainted 我在想「受污染」是不是比「被污染」要好一点
考虑如果希望两个时态更加统一的话，不知道 tainting 我是不是也可以直接用「污染」，比如说“不要仅依赖于污染来确保安全……污染只是一层保护”。当然另一种做法是把 tainted 翻译为「受污点标记」
无论如何，我们可以先发一版，同时把现阶段的翻译在术语表里记录下来
