### ISSUE TITLE
学习React部分的渲染列表章节#对数组项进行过滤codesandbox无法正确显示

### ISSUE THREAD

**Issue by yumubi** [reactjs/zh-hans.react.dev#1407]
### 错误位置: 
`https://zh-hans.react.dev/learn/rendering-lists#filtering-arrays-of-items`部分的playground的App.js的import语句
### 错误截图:

![image](https://github.com/reactjs/zh-hans.react.dev/assets/91480868/bf539128-c9e7-45a2-bd90-de7ac113d68c)
--
### 原版英文教程部分截图对比:
![image](https://github.com/reactjs/zh-hans.react.dev/assets/91480868/3fe9cb42-9859-4861-8329-a829d5039d9d)
--
### 错误原因:
codesandbox中的代码结构srcdata.js位于src同级目录
![image](https://github.com/reactjs/zh-hans.react.dev/assets/91480868/998d8ead-216e-48b7-80d6-370f408f0b4b)
--
### 建议: 修改`App.js`的`import { people } from './data.js';` 或者修改codesandbox中代码结构

**Comment by Yucohny** [comment]
This should have been solved by https://github.com/reactjs/zh-hans.react.dev/pull/1408. Thanks for your feedback.
