### ISSUE TITLE
请问react的原英文文档代码在哪

### ISSUE THREAD

**Issue by fengyunzaidushi** [reactjs/zh-hans.react.dev#1453]
![image](https://github.com/reactjs/zh-hans.react.dev/assets/53250064/05fd20b2-22c3-473c-a052-98c2f07ff187)

上面是官方网站内容，我想找到源代码，应该是.md或者.mdx格式，我在这个库中并没有找到：https://github.com/facebook/react，还是在哪个分支中，谢谢!

**Comment by loveloki** [comment]
[react 英文文档仓库](https://github.com/reactjs/react.dev)，其他语言的也可以在 [reactjs](https://github.com/reactjs) 下找到

**Comment by fengyunzaidushi** [comment]
谢谢！
