### ISSUE TITLE
rendering-lists.md 的代码块内人名翻译问题

### ISSUE THREAD

**Issue by Ant00000ny** [reactjs/zh-hans.react.dev#1527]
[这个代码块](https://github.com/reactjs/zh-hans.react.dev/blob/f519dfb44205fae4c5e24a1e6183152ad1345103/src/content/learn/rendering-lists.md?plain=1#L105C6-L127C4)在提交历史里的人名翻译一直在中英文之间反复横跳，与上下文一致的话保持中文会比较好？

**Comment by awxiaoxian2020** [comment]
欢迎提出 Pull Request~
