### ISSUE TITLE
React 中文文档译文规范：更换 `°` 为 `°C`

### ISSUE THREAD

**Issue by northword** [reactjs/zh-hans.react.dev#1570]
在规范中，提到“数字与单位之间需要添加空格”：

> 数字与单位之间加空格
> 
> ✅
> 
> > 今天达到了 39.5 ° 的高温
> 
> ❌
> 
> > 今天达到了 39.5° 的高温

这里示例不妥，有以下两点原因：

1. 常见的温度单位为摄氏度 `°C` 、华氏度 `°F` 或 开儿文温度 `K`，而不包含 `°`；
2. `°` 是一个角度单位。角度单位通常视为数字的一部分，因此不需要在数字和单位之间添加空格，类似的单位有 `%`、`'` 和 `''` 等。

此外，对于摄氏温标，需要区分 `°C` 和 `℃`，见 [摄氏温标](https://zh.wikipedia.org/wiki/%E6%91%84%E6%B0%8F%E6%B8%A9%E6%A0%87#%E7%AC%A6%E8%99%9F)。

**Comment by awxiaoxian2020** [comment]
谢谢指正，已修改。
