### ISSUE TITLE
对于“学习React-状态管理-选择State结构-第3个挑战”的翻译建议

### ISSUE THREAD

**Issue by Logarithm5314** [reactjs/zh-hans.react.dev#1572]
### 问题描述
目前React v18.3.1的文档中，“学习React-状态管理-选择State结构-第3个挑战”的中文翻译与实际语境不符。

该挑战编写了一段将鼠标移至\<li\>标签上使其高亮的代码。
对应的中文翻译将Letter翻译为“字母”，但在实际语境中代指的是代码中Letters的单数形式，即可以被Star的一行文本。
结合英文语境，Letter显然并非字母，而应为信件或邮件。个人认为“信件”或“邮件”等翻译较为符合语境，也可遵循第4个挑战的格式，使用原文Letter。

下为目前使用中的中英文截图：
#### 中文翻译
![react翻译错误-中文页面](https://github.com/user-attachments/assets/6dc5ad8f-4d47-4bae-a57d-9901bc47f4b6)

#### 英文原文
![react翻译错误-英文页面](https://github.com/user-attachments/assets/91aac86c-da25-4ad1-abf5-521afd985a98)

### 建议
“学习React-状态管理-选择State结构-第3个挑战”中的“字母”应翻译为“信件”或“邮件”，或不进行翻译而使用原文Letter。

**Comment by awxiaoxian2020** [comment]
欢迎 PR
