### ISSUE TITLE
博客存在语义不明确的翻译

### ISSUE THREAD

**Issue by FanetheDivine** [reactjs/zh-hans.react.dev#1574]
[链接](https://zh-hans.react.dev/blog/2024/04/25/react-19#support-for-custom-elements)
<img width="869" alt="屏幕截图 2024-07-29 082356" src="https://github.com/user-attachments/assets/0db068eb-2f97-4364-b540-9db3e834ee82">
这一节中出现了多个语义不明确的专有名词'属性' 事实上原文里是attributes和properties两个词
<img width="851" alt="屏幕截图 2024-07-29 082739" src="https://github.com/user-attachments/assets/43f7c70f-86f1-4e42-a53c-d86e9fbd4c54">

**Comment by polaris-dxz** [comment]
改成 attribute 属性和 property 属性好点

**Comment by loveloki** [comment]
有确切的修改想法可以直接 PR，需要讨论的话再开 issue 就行。

@FanetheDivine @polaris-dxz 你俩谁愿意提交个吗？

**Comment by FanetheDivine** [comment]
@loveloki 已经提交pr
