### ISSUE TITLE
脱围机制——使用Effect同步小节，一处翻译错误

### ISSUE THREAD

**Issue by fuxing2024** [reactjs/zh-hans.react.dev#1595]
![微信图片_20240926084735](https://github.com/user-attachments/assets/26d7895c-1c8f-46b9-a3e8-11a5b2c98da6)
![微信图片编辑_20240926084822](https://github.com/user-attachments/assets/e2b4bb85-5738-4b0a-ba4b-c005ec9da70d)
对比英文版文档，知道，这里应该是只会在每次挂载之后，而非渲染。
由于渲染和挂载是两个明确不同的概念，不修正的话容易让读者产生困惑

**Comment by loveloki** [comment]
Thanks!这里确实是翻译错误，在 #1590 中已经有提交修改。

如果有其他修改的地方欢迎提交 PR

**Comment by fuxing2024** [comment]
> Thanks!这里确实是翻译错误，在 #1590 中已经有提交修改。
> 
> 如果有其他修改的地方欢迎提交 PR
但是为什么网站里还没更改过来呢

**Comment by loveloki** [comment]
@fuxing2024 因为 PR 还没有合并，等修改完合并后就会部署新的页面，然后就可以看到了。
