### ISSUE TITLE
Feature Request: Add Collapse Feature for Left-Side Menu

### ISSUE THREAD

**Issue by aojunhao123** [reactjs/zh-hans.react.dev#1601]
**Description:**

The left-side navigation menu in the React official Chinese documentation currently lacks a collapse feature. When navigating through long lists, users have to scroll to the bottom to access other sections. This can be inconvenient, especially when switching between categories such as “**Hook**” or “**组件**”.

![image](https://github.com/user-attachments/assets/fddec42c-71c7-4004-b2c4-f63de83a5994)

**Comment by aojunhao123** [comment]
PS: I would be happy to contribute to this feature and submit a pull request  to implement the collapse functionality. Please let me know if this is something the team is open to, and I can start working on it.

**Comment by loveloki** [comment]
Hi @aojunhao123 , You should contribute to [English documentation](https://github.com/reactjs/react.dev) for this idea, and other language translations will synchronize the code.

**Comment by aojunhao123** [comment]
> Hi @aojunhao123 , You should contribute to [English documentation](https://github.com/reactjs/react.dev) for this idea, and other language translations will synchronize the code.

Yes, I have submitted the corresponding issue to the official repository.thanks！
