### ISSUE TITLE
[READ ONLY] The Glossary Sheet

### ISSUE THREAD

**Issue by tesseralis** [reactjs/zh-hans.react.dev#2]
# React 翻译参考

**相关问题讨论请移步至 #611. 本 issue 现在为只读状态**。

- 本术语表只适用于该术语作为整体概念时的翻译参考，当其作为概念的一部分时，视具体情况翻译。

## React 中英文对照表

|          术语           |      译文       |
| :---------------------: | :-------------: |
|         asserts         |      断言       |
|       Application       |      应用       |
|     breaking change     |   破坏性更改    |
|        callback         |    回调函数     |
|    Class Components     |   类式组件    |
|       Composition       |      组合       |
|  conditional rendering  |    条件渲染     |
|  controlled components  |    受控组件     |
| Cross-Cutting Concerns  |   横切关注点    |
|          data           |      数据       |
|       Declarative       |     声明式      |
|      derived state      |    派生状态     |
|        Elements         |      元素       |
|  Embedding Expressions  |   嵌入表达式    |
|     escape hatches      |    应急方案     |
|    External Plugins     |    外部插件     |
|   Function component    |    函数组件     |
|  Functional Components  |   函数式组件    |
|   function signature    |    函数签名     |
|           HOC           | 高阶函数（HOC） |
| higher-order-component  |    高阶函数     |
|     Handling Events     |    事件处理     |
|       Inheritance       |      继承       |
|         Legacy          |      过时       |
|       local state       |   内部 state    |
|          mock           |     设计稿      |
|        operator         |     运算符      |
|      prop drilling      |  prop 逐级透传  |
|     Reconciliation      |      协调       |
|         render          |      渲染       |
|        Reusable         |     可复用      |
|    shallow rendering    |    浅层渲染     |
|   Stateful Component    |   有状态组件    |
|         syntax          |      语法       |
|      Third Plugins      |   第三方插件    |
| uncontrolled components |   非受控组件    |
|      Vendor Prefix      |   浏览器引擎    |

通用

|       原文        |       译文        |
| :---------------: | :---------------: |
|   Code linters    |   代码检查工具    |
|      example      |       示例        |
|    For example    |       例如        |
|     Importing     |     如何引入      |
|  In this chapter  |      本章节       |
|       Note        |       注意        |
|      opt-in       |       可选        |
|     Overview      |       概览        |
|     Reference     |       参考        |
|      section      |       章节        |
|        Tip        |       提示        |
|     Tutorial      |       教程        |
| Try it on CodePen | 在 CodePen 上尝试 |
|    What's next    |     下节预告      |

## 有时无需翻译的内容

- 原文术语大小写一致时和下表一致的优先**不翻译**，大小写不一致的，视具体情况决定是否翻译，如需翻译，可参考**可选翻译**一列。
- 下表只适用于该术语作为整体概念时的参考，当其作为概念的一部分时，视具体情况决定是否翻译，如需翻译，可参考**可选翻译**一列。
- 中文文档中，术语的大小写和单复数请跟下表保持一致，例如原文的 `props` 不需要改为单数。

|       术语       | 可选翻译 |
| :--------------: | :------: |
|    Attributes    |          |
|      bundle      |          |
|      class       |          |
|     Consumer     |          |
|     context      |          |
| Create React App |          |
|       DOM        |          |
|      Effect      |  副作用  |
|     fallback     |       |
|      Fiber       |          |
|    fragments     |          |
|     Good/Bad     |          |
|       Hook       |          |
|       hydrate/hydration       |          |
|      mixins      |          |
|     Mutation     |          |
|     package      |    包    |
|     polyfill     |          |
|      Portal      |          |
|    PropTypes     |          |
|     Provider     |          |
|   props / prop   |          |
|      React       |          |
|       ref        |          |
|      state       |   状态   |
|       Tick       |          |
|        UI        | 用户界面 |
|       Web        |          |
|  Web Components  |          |
|     wrapper      |          |

## 不需翻译的链接：

- Wikipedia
- MDN

**Comment by yuqingc** [comment]
`Tip` 这个单词很多地方出现了，是直接不翻译，还是需要统一一下。
![image](https://user-images.githubusercontent.com/29723652/52107003-b2682980-262f-11e9-8d94-1ba9773c2e0f.png)

**Comment by caiyongmin** [comment]
`painless JavaScript testing` 这个可不可以直接翻译成 `JavaScript 测试`?

**Comment by caiyongmin** [comment]
> `Tip` 这个单词很多地方出现了，是直接不翻译，还是需要统一一下。
> ![image](https://user-images.githubusercontent.com/29723652/52107003-b2682980-262f-11e9-8d94-1ba9773c2e0f.png)
> 
> Vocabulary: (keep updating)
> 
> * Overview
> * Tip
> * Section

加一个 Note

![image](https://user-images.githubusercontent.com/11053605/52109606-0aeff480-2639-11e9-8530-1a0101a7d474.png)

**Comment by robertying** [comment]
`callback` 回调函数

Is there any need to translate it or translate all to `回调函数`?

**Comment by tesseralis** [comment]
I added `TRANSLATION.md` to the main repo: https://github.com/reactjs/zh-hans.reactjs.org/blob/cn/TRANSLATION.md

Once we've finalized the style guide of terms, let's put it in that file so that it's more discoverable.

**Comment by dear-lizhihua** [comment]
External Plugins 和 Third Plugins 如何区分？
我觉得应该细分为 外部化插件 和 第三方插件

**Comment by haimengzhang** [comment]
重用 sounds better to me.

**Comment by chenjie3323** [comment]
The `Try it on CodePen` link occurs many times in different sections.
I think the translation should be consistent. 
`在CodePen中试试`  `在CodePen中尝试` or any other translation?

**Comment by robertying** [comment]
@chenjie3323 don't forget the whitespace between English and Chinese characters.

**Comment by robertying** [comment]
How about `class`? Should we translate it?

**Comment by chenjie3323** [comment]
> @chenjie3323 don't forget the whitespace between English and Chinese characters.

Oh, thank you for pointing out that.

**Comment by BetaMee** [comment]
legacy 应该翻译为遗留 还是过时呢？

**Comment by QC-L** [comment]
@BetaMee 遗弃 或者 过时吧？其他人有何看法？

**Comment by BetaMee** [comment]
@QC-L 又看到新的叫法 废弃API，这个可能更合适一些

**Comment by QC-L** [comment]
@BetaMee 废弃吧

**Comment by Koopos** [comment]
Hooks => Hooks  Hook => Hook 这样吗？

**Comment by keyz** [comment]
@robertying 在 [Thinking in React](https://reactjs.org/docs/thinking-in-react.html#start-with-a-mock) 中的 mock 建议翻译成「设计稿」。在日常工作中，mock 一般指 designer 产出的可转化生产的 UI。这个场景中并没有「原型」或「模拟」的意思。

**Comment by QC-L** [comment]
@keyz 好的，我来修改下~

**Comment by yuqingc** [comment]
context 中的 consuming component 中的 consume 怎么翻译比较好？

**Comment by hijiangtao** [comment]
@yuqingc 这里为动词，我认为可以直译「消费」。另 react 中还存在 Provider 和 Consumer 两个特性，建议加入 glossary 规范？@QC-L

**Comment by QC-L** [comment]
@hijiangtao Provider 和  Consumer 不翻译了吧？

**Comment by hijiangtao** [comment]
我倾向于不翻译 Provider 和 Consumer，可以加入 glossary 不需翻译的内容。

**Comment by baxtergu** [comment]
deprecated需要一个统一的翻译

**Comment by QC-L** [comment]
@baxtergu 在哪篇文章，哪段？能不能给个上下文

**Comment by baxtergu** [comment]
> @baxtergu 在哪篇文章，哪段？能不能给个上下文

我在 `content/docs/reference-react.md` 里面 191 行里遇到的，我搜了一下，在很多跟 API 有关的部分都有。

![image](https://user-images.githubusercontent.com/2825625/52861559-d9fddc80-316d-11e9-912a-a46d7447fd55.png)

我觉得翻译的时候有必要统一一下

**Comment by QC-L** [comment]
@baxtergu 废弃

**Comment by chenshuai2144** [comment]
`Cross-Cutting Concerns ` 这个应该怎么翻译，感觉是个专有的名词，但是却不好理解

**Comment by seognil** [comment]
@chenshuai2144 
横切关注点
https://en.wikipedia.org/wiki/Cross-cutting_concern

**Comment by ycjcl868** [comment]
PropTypes 也不需要翻译吧

**Comment by ycjcl868** [comment]
warning 需要统一下

**Comment by QC-L** [comment]
@ycjcl868 警告？
PropTypes 已添加

**Comment by QC-L** [comment]
@chenshuai2144 横切关注点（Cross-Cutting Concerns） 这样翻译吧，加上英文

**Comment by dear-lizhihua** [comment]
section, previous section, next section, current
这种也会有不一致的，比如说：前一章节、前面章节、上一章节、上节、这节、当前章节，很灵活了

**Comment by baxtergu** [comment]
Promise、polyfill 是否也加入不用翻译的内容？reference-react.md 中包含这两个词

**Comment by QC-L** [comment]
@baxtergu 已添加

**Comment by bailnl** [comment]
Web Components 不需要翻译吧。

**Comment by MrPluto** [comment]
Try it on CodePen 是否需要翻译？

**Comment by QC-L** [comment]
@MrPluto 翻译，在 CodePen 上尝试

**Comment by infinnie** [comment]
class 翻译成类吧…

**Comment by infinnie** [comment]
BTW render props 怎么翻译

**Comment by ChiuMungZitAlexander** [comment]
React Fiber, translate it or not?

**Comment by QC-L** [comment]
@ChiuMungZitAlexander I don't think so.

**Comment by QC-L** [comment]
@infinnie 特殊情况下翻译，其他情况下都不翻译。

**Comment by thoamsy** [comment]
`Legacy API` 翻译成 **过时 API** 和 **deprecated** 区分下？

**Comment by Jokcy** [comment]
@QC-L higher-order-component是否也不需要翻译，或者高阶组件？

**Comment by QC-L** [comment]
@thoamsy 嗯，可以讨论下。

**Comment by QC-L** [comment]
@thoamsy 嗯，可以讨论下。

**Comment by QC-L** [comment]
@Jokcy 高阶组件

**Comment by Jokcy** [comment]
@QC-L 缩写HOC是否也一并翻译呢？

**Comment by QC-L** [comment]
@Jokcy 翻译，然后带上缩写 `高阶组件（HOC）`

**Comment by Jokcy** [comment]
@QC-L 把`HOC`翻译成`高阶组件（HOC）`在`higher-order-component.md`中貌似不怎么好，因为出现频率太高来，比如会变成这个样子：

>注意一个高阶组件(HOC)不会修改传入的组件，也不会使用继承的方式来拷贝他的行为。相反，一个高阶组件(HOC)**组合**原始组件的方式是通过把他**包装**进入一个容器组件。一个高阶组件(HOC)是一个没有任何副作用的纯粹的方法。

我建议

1. 直接翻译成高阶组件
2. 在最开始说明`higher-order-compoent`是高阶组件的地方注释（之后简称HOC），然后后面不翻译

**Comment by QC-L** [comment]
@Jokcy 那 HOC 的地方就不翻译了，在文中第一个出现 HOC 的地方，加译注。

**Comment by Jokcy** [comment]
@QC-L 好的

**Comment by QC-L** [comment]
@thoamsy 已经区分了，查看下

**Comment by jimczj** [comment]
pull request 直接用 PR 代替可以吗，还是翻译成“拉取请求”？

**Comment by QC-L** [comment]
@jimczj 直接用 PR

**Comment by robertying** [comment]
@jimczj 不翻译，用 pull request 呢？感觉缩写成 pr 也没必要。

**Comment by zcfan** [comment]
@tesseralis reuse 出现了两次，我看到有权限编辑，直接改了

**Comment by Enki-y** [comment]
Hooks怎么翻译啊？

**Comment by baxtergu** [comment]
> Hooks怎么翻译啊？

不用翻，目前文档里 Hook 都没翻

**Comment by lesenelir** [comment]
我正在阅读https://beta.reactjs.org/learn，这一章节的内容。
我比较好奇，markup在我看来应该翻译为“标签”会比现有“标记”更好一点？

**Comment by lesenelir** [comment]
我正在阅读 https://beta.reactjs.org/learn
我比较好奇，markup在我看来应该翻译为“标签”会比现有“标记”更好一点？

**Comment by zifeiyu666** [comment]
哈喽，大家，memoization 这个词是否不应该去翻译啊？感觉不管怎么翻译都没有英文这个单词表达的更加清晰？

**Comment by awxiaoxian2020** [comment]
> 哈喽，大家，memoization 这个词是否不应该去翻译啊？感觉不管怎么翻译都没有英文这个单词表达的更加清晰？

请移步至 #611

**Comment by Yucohny** [comment]
See https://github.com/reactjs/zh-hans.react.dev/wiki/The-Glossary-Sheet.
